version: '3'
services: 
  nginx:
    image: nginx:mainline-apline
    container_name: nginx
    restart: always
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/html:/etc/nginx/html/:rw
      - ./nginx/.well-known:/usr/share/nginx/html/.well-known:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx:rw
    links: 
      - php:php

  sql:
    image: mariadb:latest
    container_name: sql
    expose: 
      - 3306
    volumes: 
      - ./mysql/data:/var/lib/mysql
    env_file: 
      - ./.env
    # environment: 
    # - MYSQL_ROOT_PASSWORD
    # - MYSQL_DATABASE
    # - MYSQL_USER
    # - MYSQL_PASSWORD

  php:
    image: 7.2-fpm-alpine
    container_name: fpm
    restart: always
    volumes: 
    - ./nginx/html:/usr/share/nginx/html

  phpmyadmin:
    image:
    container_name: phpmyadmin
    ports: 
      - 9999:80
    env_file: 
      - ./.env
    # environment: 
    # - MYSQL_ROOT_PASSWORD
    # - MYSQL_DATABASE
    # - MYSQL_USER
    # - MYSQL_PASSWORD

  # ssl:

